#!/bin/bash
script_name=$(realpath $0)
script_dir=$(dirname $script_name)
curdir=$(dirname $script_dir)

name=$1
branch=$2
if [ -z $branch ]; then
  branch=master
fi

pushd `pwd`
cd $curdir
fail=1
if [ -d $name ]; then
  cd $name
  git checkout $branch
  git pull origin $branch
else
  git clone git@github.lan:cpp/$name.git
  cd $name
  git checkout $branch
  mkdir build
fi
cd build
cmake ..
cmake --build .
popd
